<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ApplicationIcon>BulkFileRenamerIcon.ico</ApplicationIcon>
	  <Authors>$(IvanicJakub)</Authors>
	  <Company>$(Jakub Ivanič - Orava Games)</Company>
	  <PackageIcon>BulkFileRenamerIcon.png</PackageIcon>
	  <Description>Bulk File Renamer is a lightweight, user-friendly tool designed for quickly renaming multiple files in a folder. Whether you're organizing photos, documents, or any type of file, this app allows you to rename your files in bulk with customizable options. The app provides:
- Simple folder selection via drag-and-drop or browsing.
- A starting name that is combined with customizable suffixes and file numbering.
- Optional features like skipping hidden/system files and using leading zeros for file numbering.
- A live preview of renamed files before applying changes, making it easier to review and confirm.

It's perfect for anyone needing a fast and efficient file renaming solution without complex setups!</Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="BulkFileRenamerIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="BulkFileRenamerIcon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="DarkTheme.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="LightTheme.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
